### ISSUE TITLE
Error accessing data via git lfs

### ISSUE THREAD

**Issue by nicholsn** [CapraLab/cosmis#2]
Hi and thanks for making this resource publicly available. 

I am trying to use `git lfs` to download the dataset that you are distributing but I'm getting the following error:

```
(base) ✔ ~/Code/cosmis [master|✔]
18:57 $ git lfs fetch
fetch: Fetching reference refs/heads/master
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/CapraLab/cosmis.git/info/lfs'
```

Any chance these data files are available for download elsewhere or do you have any suggestions for how I might access these data?

**Comment by computbiolgeek** [comment]
Hello, thanks for your interest! We are in the process of sorting this issue out. But in terms of accessing the larger data files, we have also made them available here: https://figshare.com/articles/dataset/Source_Data/19742404. 

Besides this, please also note that we are repackaging the method into an installable Python package. There will be some restructuring of the folders and scripts.

**Comment by nicholsn** [comment]
Thanks for the link and info - will look forward to this method being available as a python package!
